"""initial schema — users, targets, scans, findings, tool_jobs, reports, alerts, exploit_attempts, log_entries

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-03

Hand-authored (not autogenerated) to exactly mirror models/*.py at the
Phase-1 foundation. Every table, enum, FK, and index here has a 1:1
counterpart in the SQLAlchemy models — see models/__init__.py for the
canonical list this migration must stay in sync with.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # ---- users ---------------------------------------------------------
    user_role = pg.ENUM("admin", "analyst", "viewer", name="userrole", create_type=False)
    user_role.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("username", sa.String(64), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), server_default="", nullable=False),
        sa.Column(
            "role", user_role, nullable=False, server_default="viewer"
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("mfa_secret", sa.String(64), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_username", "users", ["username"], unique=True)

    # ---- targets ---------------------------------------------------------
    target_type = pg.ENUM(
        "domain", "ip", "ip_range", "url", "wireless_ssid", name="targettype", create_type=False
    )
    target_type.create(op.get_bind(), checkfirst=True)
    target_status = pg.ENUM(
        "pending_auth", "authorized", "active", "archived", name="targetstatus", create_type=False
    )
    target_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "targets",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("value", sa.String(512), nullable=False),
        sa.Column("type", target_type, nullable=False),
        sa.Column(
            "status", target_status, nullable=False, server_default="pending_auth"
        ),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "authorization_reference", sa.String(255), server_default="", nullable=False
        ),
        sa.Column(
            "owner_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_targets_value", "targets", ["value"])
    op.create_index("ix_targets_owner_id", "targets", ["owner_id"])

    # ---- scans ---------------------------------------------------------
    scan_type = pg.ENUM(
        "recon", "port_scan", "vuln_scan", "web_scan", "wireless_scan", name="scantype", create_type=False
    )
    scan_type.create(op.get_bind(), checkfirst=True)
    scan_status = pg.ENUM(
        "queued", "running", "completed", "failed", "cancelled", name="scanstatus", create_type=False
    )
    scan_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "scans",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "target_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("targets.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "initiated_by",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("scan_type", scan_type, nullable=False),
        sa.Column("tool", sa.String(64), nullable=False),
        sa.Column("status", scan_status, nullable=False, server_default="queued"),
        sa.Column("celery_task_id", sa.String(64), nullable=True),
        sa.Column("parameters", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column("raw_output", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column("progress_pct", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_scans_target_id", "scans", ["target_id"])
    op.create_index("ix_scans_status", "scans", ["status"])

    # ---- findings ---------------------------------------------------------
    severity = pg.ENUM("critical", "high", "medium", "low", "info", name="severity", create_type=False)
    severity.create(op.get_bind(), checkfirst=True)
    finding_status = pg.ENUM(
        "open",
        "confirmed",
        "false_positive",
        "remediated",
        "accepted_risk",
        name="findingstatus",
        create_type=False,
    )
    finding_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "findings",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "target_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("targets.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "scan_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("scans.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("title", sa.String(512), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("severity", severity, nullable=False),
        sa.Column("status", finding_status, nullable=False, server_default="open"),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cvss_vector", sa.String(128), nullable=True),
        sa.Column("cve_ids", pg.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column(
            "mitre_techniques", pg.ARRAY(sa.String()), server_default="{}", nullable=False
        ),
        sa.Column("affected_host", sa.String(255), server_default="", nullable=False),
        sa.Column("affected_port", sa.Integer(), nullable=True),
        sa.Column("affected_service", sa.String(128), server_default="", nullable=False),
        sa.Column("evidence", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column("remediation", sa.Text(), server_default="", nullable=False),
        sa.Column("source_tool", sa.String(64), server_default="", nullable=False),
        sa.Column("ai_analysis", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_findings_target_id", "findings", ["target_id"])
    op.create_index("ix_findings_scan_id", "findings", ["scan_id"])
    op.create_index("ix_findings_severity", "findings", ["severity"])
    op.create_index("ix_findings_status", "findings", ["status"])

    # ---- tool_jobs ---------------------------------------------------------
    tool_category = pg.ENUM(
        "recon",
        "scanning",
        "web",
        "exploitation",
        "password",
        "post_exploit",
        "network",
        "wireless",
        "blueteam",
        "forensics",
        name="toolcategory",
        create_type=False,
    )
    tool_category.create(op.get_bind(), checkfirst=True)
    tool_job_status = pg.ENUM(
        "queued", "running", "completed", "failed", "cancelled", "timeout", name="tooljobstatus", create_type=False
    )
    tool_job_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "tool_jobs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "target_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("targets.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column(
            "requested_by",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=False,
        ),
        sa.Column("category", tool_category, nullable=False),
        sa.Column("tool_name", sa.String(64), nullable=False),
        sa.Column("command", sa.String(2048), server_default="", nullable=False),
        sa.Column("status", tool_job_status, nullable=False, server_default="queued"),
        sa.Column("celery_task_id", sa.String(64), nullable=True),
        sa.Column("stdout_log", sa.Text(), server_default="", nullable=False),
        sa.Column("stderr_log", sa.Text(), server_default="", nullable=False),
        sa.Column("parsed_output", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_tool_jobs_target_id", "tool_jobs", ["target_id"])
    op.create_index("ix_tool_jobs_category", "tool_jobs", ["category"])
    op.create_index("ix_tool_jobs_status", "tool_jobs", ["status"])

    # ---- reports ---------------------------------------------------------
    report_format = pg.ENUM("pdf", "json", "html", name="reportformat", create_type=False)
    report_format.create(op.get_bind(), checkfirst=True)
    report_status = pg.ENUM("generating", "ready", "failed", name="reportstatus", create_type=False)
    report_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "reports",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "target_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("targets.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "generated_by",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=False,
        ),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("format", report_format, nullable=False, server_default="pdf"),
        sa.Column("status", report_status, nullable=False, server_default="generating"),
        sa.Column("file_path", sa.String(512), nullable=True),
        sa.Column("summary", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column("finding_ids", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_reports_target_id", "reports", ["target_id"])

    # ---- alerts ---------------------------------------------------------
    alert_severity = pg.ENUM("critical", "high", "medium", "low", name="alertseverity", create_type=False)
    alert_severity.create(op.get_bind(), checkfirst=True)
    alert_status = pg.ENUM(
        "new", "acknowledged", "investigating", "resolved", "false_positive", name="alertstatus", create_type=False
    )
    alert_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "alerts",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("description", sa.String(2048), server_default="", nullable=False),
        sa.Column("severity", alert_severity, nullable=False),
        sa.Column("status", alert_status, nullable=False, server_default="new"),
        sa.Column("source", sa.String(64), server_default="", nullable=False),
        sa.Column("rule_id", sa.String(128), server_default="", nullable=False),
        sa.Column("mitre_techniques", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column("related_log_ids", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column("raw", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_alerts_created_at", "alerts", ["created_at"])
    op.create_index("ix_alerts_severity", "alerts", ["severity"])
    op.create_index("ix_alerts_status", "alerts", ["status"])

    # ---- exploit_attempts ---------------------------------------------
    # Governance ledger only — every row requires explicit human approval
    # (approved_by) before workers/exploit_tasks.py would ever be allowed
    # to run anything against it, and that worker is intentionally not
    # part of this build. This table exists so the approval workflow and
    # audit trail are in place regardless.
    exploit_status = pg.ENUM(
        "pending_approval",
        "approved",
        "denied",
        "running",
        "success",
        "failed",
        name="exploitstatus",
        create_type=False,
    )
    exploit_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "exploit_attempts",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "finding_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("findings.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "target_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("targets.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "requested_by",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=False,
        ),
        sa.Column(
            "approved_by",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("module", sa.String(255), nullable=False),
        sa.Column("payload", sa.String(255), server_default="", nullable=False),
        sa.Column("options", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column(
            "status", exploit_status, nullable=False, server_default="pending_approval"
        ),
        sa.Column("result", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column("justification", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_exploit_attempts_target_id", "exploit_attempts", ["target_id"])
    op.create_index("ix_exploit_attempts_status", "exploit_attempts", ["status"])

    # ---- log_entries ---------------------------------------------------------
    log_source = pg.ENUM(
        "suricata", "wazuh", "syslog", "firewall", "auth", "custom", name="logsource", create_type=False
    )
    log_source.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "log_entries",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("source", log_source, nullable=False),
        sa.Column("host", sa.String(255), server_default="", nullable=False),
        sa.Column("event_type", sa.String(128), server_default="", nullable=False),
        sa.Column("severity", sa.String(32), server_default="info", nullable=False),
        sa.Column("message", sa.String(2048), server_default="", nullable=False),
        sa.Column("raw", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column("matched_rules", pg.JSONB(), server_default="{}", nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_log_entries_ingested_at", "log_entries", ["ingested_at"])
    op.create_index("ix_log_entries_source", "log_entries", ["source"])


def downgrade() -> None:
    op.drop_table("log_entries")
    op.drop_table("exploit_attempts")
    op.drop_table("alerts")
    op.drop_table("reports")
    op.drop_table("tool_jobs")
    op.drop_table("findings")
    op.drop_table("scans")
    op.drop_table("targets")
    op.drop_table("users")

    bind = op.get_bind()
    for enum_name in (
        "logsource",
        "exploitstatus",
        "alertstatus",
        "alertseverity",
        "reportstatus",
        "reportformat",
        "tooljobstatus",
        "toolcategory",
        "findingstatus",
        "severity",
        "scanstatus",
        "scantype",
        "targetstatus",
        "targettype",
        "userrole",
    ):
        pg.ENUM(name=enum_name).drop(bind, checkfirst=True)
